[package]
name = "rustupolis"
version = "0.0.1"
authors = ["Michael Wagner <wagner.mchl@googlemail.com>"]
readme = "README.md"

[lib]
name = "rustupolis"
path = "src/lib.rs"

[[example]]
name = "hello_world"
path = "examples/hello_world/main.rs"

[[test]]
name = "startup_test"
path = "tests/startup.rs"

[[test]]
name = "basic_functions_test"
path = "tests/basic_functions.rs"

[dependencies]
log = "0.3.8"
clap = "2"
